import { useUser } from "./context/AppContext.jsx";

const TRANSLATIONS = {
  English: {
    Overview: "Overview",
    Planning: "Planning",
    Money: "Money",
    Account: "Account",
    Dashboard: "Dashboard",
    "Net Worth": "Net Worth",
    "Reports & Export": "Reports & Export",
    "Budget Planner": "Budget Planner",
    Goals: "Goals",
    Retirement: "Retirement",
    Asset: "Asset",
    Liability: "Liability",
    "Add Bill": "Add Bill",
    "Add Subscription": "Add Subscription",
    "Debt Manager": "Debt Manager",
    Calculators: "Calculators",
    Investments: "Investments",
    "Bank & Payments": "Bank & Payments",
    "Bills & Subs": "Bills & Subs",
    "Tax Calculator": "Tax Calculator",
    "Family Mode": "Family Mode",
    Settings: "Settings",
    "Smart Money": "Smart Money",
    "Financial Planner": "Financial Planner",
    "Light Mode": "Light Mode",
    "Dark Mode": "Dark Mode",
    "Budget Planner": "Budget Planner",
    "Track and manage your monthly spending":
      "Track and manage your monthly spending",
    "Add Category": "Add Category",
    "New Budget Category": "New Budget Category",
    Cancel: "Cancel",
    "Financial Calculators": "Financial Calculators",
    "Plan your loans, investments, and savings with precision":
      "Plan your loans, investments, and savings with precision",
    "Loan Calculator": "Loan Calculator",
    "EMI Calculator": "EMI Calculator",
    "Savings Growth": "Savings Growth",
    "Investment Return": "Investment Return",
    "Debt Manager": "Debt Manager",
    "Track and accelerate your debt payoff journey":
      "Track and accelerate your debt payoff journey",
    "Add Debt": "Add Debt",
    "Add Debt Account": "Add Debt Account",
    "Goals Tracker": "Goals Tracker",
    "Set, track, and achieve your financial milestones":
      "Set, track, and achieve your financial milestones",
    "New Goal": "New Goal",
    "Create New Goal": "Create New Goal",
    "Add Contribution": "Add Contribution",
    "Add Funds": "Add Funds",
    "Net Worth": "Net Worth",
    "Your complete financial balance sheet":
      "Your complete financial balance sheet",
    "Reports & Exporting": "Reports & Exporting",
    "Financial reports, tax summaries and data exports":
      "Financial reports, tax summaries and data exports",
    "Export All": "Export All",
    "Monthly Report": "Monthly Report",
    "Yearly Report": "Yearly Report",
    "Tax Report": "Tax Report",
    "Custom Report": "Custom Report",
    "Showing:": "Showing:",
    "Total Income": "Total Income",
    "Total Expenses": "Total Expenses",
    "Net Savings": "Net Savings",
    "Savings Rate": "Savings Rate",
    Income: "Income",
    Expenses: "Expenses",
    Savings: "Savings",
    "Monthly Spend Trend": "Monthly Spend Trend",
    "Spend by Category": "Spend by Category",
    "Auto-synced Transactions": "Auto-synced Transactions",
    "Sync Activity (This Week)": "Sync Activity (This Week)",
    "Sync Status": "Sync Status",
    "Sync All Now": "Sync All Now",
    Description: "Description",
    Bank: "Bank",
    Category: "Category",
    Date: "Date",
    Status: "Status",
    Amount: "Amount",
    Synced: "Synced",
    Pending: "Pending",
    "Connect Account / Wallet": "Connect Account / Wallet",
    Live: "Live",
    "Current Balance": "Current Balance",
    "Last synced": "Last synced",
    "Connect new account": "Connect new account",
    "Connected Accounts": "Connected Accounts",
    "Total Balance": "Total Balance",
    "Credit Balances": "Credit Balances",
    "Digital Wallets": "Digital Wallets",
    "Auto-pay enabled": "Auto-pay enabled",
    Auto: "Auto",
    Manual: "Manual",
    Pay: "Pay",
    Pause: "Pause",
    Resume: "Resume",
    Bills: "Bills",
    Subscriptions: "Subscriptions",
    Bill: "Bill",
    Month: "Month",
    Investments: "Investments",
    "Save Rate": "Save Rate",
    "4-Month Overview": "4-Month Overview",
    "Expense Breakdown": "Expense Breakdown",
    "Month-by-Month Breakdown": "Month-by-Month Breakdown",
    "Year-over-Year Summary": "Year-over-Year Summary",
    "5-Year Financial History": "5-Year Financial History",
    "Tax-Ready Summary": "Tax-Ready Summary",
    "Gross Income": "Gross Income",
    "Pre-tax Adjustments": "Pre-tax Adjustments",
    "Adjusted Gross Income": "Adjusted Gross Income",
    "Standard Deduction": "Standard Deduction",
    "Taxable Income": "Taxable Income",
    "Federal Income Tax": "Federal Income Tax",
    "State Tax (est.)": "State Tax (est.)",
    "FICA / Payroll Tax": "FICA / Payroll Tax",
    "TOTAL TAX OWED": "TOTAL TAX OWED",
    "After-Tax Income": "After-Tax Income",
    "Bills & Subscriptions": "Bills & Subscriptions",
    "Track upcoming bills, recurring payments and subscriptions":
      "Track upcoming bills, recurring payments and subscriptions",
    "Investment Tracking": "Investment Tracking",
    "Stocks, crypto, mutual funds · portfolio analytics & risk":
      "Stocks, crypto, mutual funds · portfolio analytics & risk",
    "Add Holding": "Add Holding",
    "Portfolio Value": "Portfolio Value",
    "Total Gain/Loss": "Total Gain/Loss",
    overall: "overall",
    "Annual Dividends": "Annual Dividends",
    "est. income": "est. income",
    "Portfolio Beta": "Portfolio Beta",
    "vs market (1.0)": "vs market (1.0)",
    "Ticker Symbol": "Ticker Symbol",
    "Asset Category": "Asset Category",
    "Full Name": "Full Name",
    Sector: "Sector",
    "Shares / Units": "Shares / Units",
    "Avg Cost / Share ($)": "Avg Cost / Share ($)",
    "Current Price ($)": "Current Price ($)",
    Beta: "Beta",
    "Risk Level": "Risk Level",
    "Sort: Value": "Sort: Value",
    "Sort: Gain%": "Sort: Gain%",
    "Sort: Risk": "Sort: Risk",
    "Sort: Ticker": "Sort: Ticker",
    Asset: "Asset",
    Category: "Category",
    Shares: "Shares",
    "Avg Cost": "Avg Cost",
    Price: "Price",
    Value: "Value",
    "Gain/Loss": "Gain/Loss",
    Return: "Return",
    Risk: "Risk",
    "Annual Dividend Income": "Annual Dividend Income",
    "Dividend Yield (Portfolio)": "Dividend Yield (Portfolio)",
    "Highest Yielder": "Highest Yielder",
    "Next Ex-Div Date": "Next Ex-Div Date",
    "Portfolio vs Benchmarks": "Portfolio vs Benchmarks",
    "Monthly Dividends": "Monthly Dividends",
    "Risk Profile Radar": "Risk Profile Radar",
    "Asset Class Allocation": "Asset Class Allocation",
    "Sector Allocation": "Sector Allocation",
    "Concentration Warning": "Concentration Warning",
    "Next Ex-Div Date": "Next Ex-Div Date",
    Price: "Price",
    Return: "Return",
    Overall: "Overall",
    "Tax Calculator": "Tax Calculator",
    "Estimate your 2024 federal and state income taxes":
      "Estimate your 2024 federal and state income taxes",
    "Retirement Planner": "Retirement Planner",
    "Model your path to financial independence":
      "Model your path to financial independence",
    "Family Mode": "Family Mode",
    "Shared finances, expense splitting and family budgeting":
      "Shared finances, expense splitting and family budgeting",
    "Add Member": "Add Member",
    "Add Family Member": "Add Family Member",
    "Full Name": "Full Name",
    "Email Address": "Email Address",
    Role: "Role",
    "Financial Details": "Financial Details",
    "Monthly Income ($)": "Monthly Income ($)",
    "Budget Share ($)": "Budget Share ($)",
    "Add First Member": "Add First Member",
    Overview: "Overview",
    Members: "Members",
    Budgets: "Budgets",
    Splits: "Splits",
    Permissions: "Permissions",
    "Financial Dashboard": "Financial Dashboard",
    "Complete analytics overview · April 2026":
      "Complete analytics overview · April 2026",
    Customize: "Customize",
    "Profile Information": "Profile Information",
    "Update your personal details and profile picture":
      "Update your personal details and profile picture",
    Profile: "Profile",
    Notifications: "Notifications",
    Security: "Security",
    Display: "Display",
    Data: "Data",
    "Manage your account, preferences and security":
      "Manage your account, preferences and security",
    Language: "Language",
    "Save Profile": "Save Profile",
    "Notification Preferences": "Notification Preferences",
    "Control what alerts and updates you receive":
      "Control what alerts and updates you receive",
    "Save Preferences": "Save Preferences",
    "Change Password": "Change Password",
    "Use a strong, unique password": "Use a strong, unique password",
    "Security Options": "Security Options",
    "Save Security Settings": "Save Security Settings",
    "Active Sessions": "Active Sessions",
    "Display & Appearance": "Display & Appearance",
    "Customize how WealthPath looks and feels":
      "Customize how WealthPath looks and feels",
    "Save Display Settings": "Save Display Settings",
    "Import & Export": "Import & Export",
    "Move your financial data in and out of WealthPath":
      "Move your financial data in and out of WealthPath",
    "Export All Data (CSV)": "Export All Data (CSV)",
    "Download all your data as a spreadsheet":
      "Download all your data as a spreadsheet",
    "Export Financial Report": "Export Financial Report",
    "Download a full PDF report of your finances":
      "Download a full PDF report of your finances",
    "Export to Excel": "Export to Excel",
    "Download all data in Excel format (.xlsx)":
      "Download all data in Excel format (.xlsx)",
    "Export Raw Data (JSON)": "Export Raw Data (JSON)",
    "Machine-readable export for developers":
      "Machine-readable export for developers",
    "Connected Services": "Connected Services",
    "Manage external integrations": "Manage external integrations",
    "Danger Zone": "Danger Zone",
    "Irreversible actions — proceed with caution":
      "Irreversible actions — proceed with caution",
    "Export Complete": "Export Complete",
    "Your file has been downloaded.": "Your file has been downloaded.",
    Name: "Name",
    "Amount ($)": "Amount ($)",
    Frequency: "Frequency",
    Category: "Category",
    "Due Day (1–31)": "Due Day (1–31)",
    "Icon Name (e.g. Home, Zap)": "Icon Name (e.g. Home, Zap)",
    "Logo URL": "Logo URL",
    Add: "Add",
  },
  Khmer: {
    Overview: "ទិដ្ឋភាពទូទៅ",
    Planning: "ការធ្វើផែនការ",
    Money: "សាច់ប្រាក់",
    Account: "គណនី",
    Dashboard: "ផ្ទាំងព័ត៌មានទូទៅ",
    "Net Worth": "ទ្រព្យសកម្មសុទ្ធ",
    "Reports & Export": "របាយការណ៍ និង ធ្វើបញ្ជូន",
    "Budget Planner": "ផែនការថវិកា",
    Goals: "គោលដៅ",
    Retirement: "វ័យចូលនិវត្តន៍",
    "Debt Manager": "គ្រប់គ្រងការខ្ចីប្រាក់",
    Calculators: "ម៉ាស៊ីនគណនា",
    Investments: "ការវិនិយោគ",
    "Bank & Payments": "ធនាគារ និង ការទូទាត់",
    Asset: "ទ្រព្យសកម្ម",
    Liability: "បំណុល",
    "Add Bill": "បន្ថែមវិក័យប័ត្រ",
    "Add Subscription": "បន្ថែមការចុះឈ្មោះ",
    "Bills & Subs": "វិក័យប័ត្រ និង សេវាចុះឈ្មោះ",
    "Tax Calculator": "ការគណនាពន្ធ",
    "Family Mode": "គម្រោងថវិការក្នុងគ្រួសារ",
    Settings: "ការកំណត់",
    "Smart Money": "ប្រាក់ឆ្លាត",
    "Financial Planner": "កម្មវិធីមាន់ហិរញ្ញវត្ថុ",
    "Light Mode": "របៀបភ្លឺ",
    "Dark Mode": "របៀបងងឹត",
    "Track and manage your monthly spending":
      "តាមដាន និងគ្រប់គ្រងការចំណាយប្រចាំខែ ប្រចាំឆ្នាំរបស់អ្នក",
    "Add Category": "បន្ថែមប្រភេទ",
    "New Budget Category": "ប្រភេទថវិកាថ្មី",
    Cancel: "បោះបង់",
    "Financial Calculators": "ម៉ាស៊ីនគណនាហិរញ្ញវត្ថុ",
    "Plan your loans, investments, and savings with precision":
      "គណនាការកម្ចី, វិនិយោគ និងសន្សំប្រាក់ដោយភាពត្រឹមត្រូវ",
    "Loan Calculator": "គណនាកម្ចី",
    "EMI Calculator": "គណនាសងប្រាក់",
    "Savings Growth": "ការសន្សំប្រាក់",
    "Investment Return": "ផលចំណេញវិនិយោគ",
    "Track and accelerate your debt payoff journey":
      "តាមដានដំណើរការសងប្រាក់អោយបានទាន់ពេលវេលា",
    "Add Debt": "បន្ថែមការខ្ចីប្រាក់",
    "Add Debt Account": "បន្ថែមគណនីខ្ចីប្រាក់",
    "Goals Tracker": "ការកំណត់និងតាមដានគោលដៅ",
    "Set, track, and achieve your financial milestones":
      "កំណត់ តាមដាន និងសម្រេចគោលដៅហិរញ្ញវត្ថុ",
    "New Goal": "គោលដៅថ្មី",
    "Create New Goal": "បង្កើតគោលដៅថ្មី",
    "Add Contribution": "បន្ថែមចំណូល",
    "Add Funds": "បន្ថែមប្រាក់",
    "Your complete financial balance sheet":
      "តារាងតុល្យភាពហិរញ្ញវត្ថុសរុបរបស់អ្នក",
    "Reports & Exporting": "របាយការណ៍ និង ការនាំចេញ",
    "Financial reports, tax summaries and data exports":
      "របាយការណ៍ហិរញ្ញវត្ថុ សង្ខេបពន្ធ និងការនាំចេញទិន្នន័យ",
    "Export All": "នាំចេញទាំងអស់",
    "Monthly Report": "របាយការណ៍ប្រចាំខែ",
    "Yearly Report": "របាយការណ៍ប្រចាំឆ្នាំ",
    "Tax Report": "របាយការណ៍ពន្ធ",
    "Custom Report": "របាយការណ៍ប្តូរតាមតម្រូវការ",
    "Showing:": "បង្ហាញ៖",
    "Total Income": "ចំណូលសរុប",
    "Total Expenses": "ចំណាយសរុប",
    "Net Savings": "សន្សំសុទ្ធ",
    "Savings Rate": "អត្រាសន្សំប្រាក់",
    Income: "ចំណូល",
    Expenses: "ចំណាយ",
    Savings: "សន្សំប្រាក់",
    "Monthly Spend Trend": "ទិសដៅចំណាយប្រចាំខែ",
    "Spend by Category": "ចំណាយតាមប្រភេទ",
    "Auto-synced Transactions": "ប្រតិបត្តិការដែលបានសមរម្យដោយស្វ័យប្រវត្តិ",
    "Sync Activity (This Week)": "សកម្មភាពសមរម្យ (សប្តាហ៍នេះ)",
    "Sync Status": "ស្ថានភាពសមរម្យ",
    "Sync All Now": "សមរម្យទាំងអស់ឥឡូវនេះ",
    Description: "ពិពណ៌នា",
    Bank: "ធនាគារ",
    Category: "ប្រភេទ",
    Date: "កាលបរិច្ឆេទ",
    Status: "ស្ថានភាព",
    Amount: "ចំនួន",
    Synced: "បានសមរម្យ",
    Pending: "កំពុងរង់ចាំ",
    "Connect Account / Wallet": "ភ្ជាប់គណនី / កាបូបឌីជីថល",
    Live: "ផ្ទាល់",
    "Current Balance": "សមតុល្យបច្ចុប្បន្ន",
    "Last synced": "បានសមរម្យនៅចុងក្រោយ",
    "Connect new account": "ភ្ជាប់គណនីថ្មី",
    "Connected Accounts": "គណនីដែលបានភ្ជាប់",
    "Total Balance": "សមតុល្យសរុប",
    "Credit Balances": "សមតុល្យឥណទាន",
    "Digital Wallets": "កាបូបឌីជីថល",
    "Auto-pay enabled": "បើកស្វ័យប្រវត្តិសងប្រាក់",
    Auto: "ស្វ័យ",
    Manual: "ដៃគូ",
    Pay: "បង់",
    Pause: "បញ្ឈប់",
    Resume: "បន្ត",
    Bills: "វិក័យប័ត្រ",
    Subscriptions: "ការចុះឈ្មោះ",
    Bill: "វិក័យប័ត្រ",
    Month: "ខែ",
    Investments: "ការវិនិយោគ",
    "Save Rate": "អត្រាសន្សំប្រាក់",
    "4-Month Overview": "ទិដ្ឋភាពទូទៅ 4 ខែ",
    "Expense Breakdown": "ការបែងចែកចំណាយ",
    "Month-by-Month Breakdown": "ការបំបែកតាមខែ",
    "Year-over-Year Summary": "សង្ខេបប្រចាំឆ្នាំ",
    "5-Year Financial History": "ប្រវត្តិហិរញ្ញវត្ថុ 5 ឆ្នាំ",
    "Tax-Ready Summary": "សង្ខេបពន្ធ",
    "Gross Income": "ចំណូលសរុប",
    "Pre-tax Adjustments": "ការកែប្រែមុនពន្ធ",
    "Adjusted Gross Income": "ចំណូលសរុបដែលបានកែប្រែ",
    "Standard Deduction": "ការដកស្រង់ស្តង់ដារ",
    "Taxable Income": "ចំណូលដែលគិតពន្ធ",
    "Federal Income Tax": "ពន្ធចំណូលសហព័ន្ធ",
    "State Tax (est.)": "ពន្ធរដ្ឋ (សន្និដ្ឋាន)",
    "FICA / Payroll Tax": "ពន្ធ FICA / ថ្នាក់ប្រាក់ខែ",
    "TOTAL TAX OWED": "ពន្ធសរុបដែលត្រូវសង",
    "After-Tax Income": "ចំណូលក្រោយពន្ធ",
    "Bank & Payment Integration": "ការរួមបញ្ចូលធនាគារ និងការទូទាត់",
    "Connect and sync all your financial accounts in one place":
      "ភ្ជាប់ទៅកាន គណនីហិរញ្ញវត្ថុទាំងអស់របស់អ្នកក្នុងកន្លែងមួយ",
    "Track upcoming bills, recurring payments and subscriptions":
      "តាមដានវិក័យប័ត្រត្រូវបង់, ការទូទាត់ម្នាក់ៗ និងការចុះឈ្មោះ",
    "Investment Tracking": "តាមដានការវិនិយោគ",
    "Stocks, crypto, mutual funds · portfolio analytics & risk":
      "ភាគហ៊ុន, គ្រីបតូ, មូលនិធិរួម · វិភាគផតថលីយ៉ូ និងហានិភ័យ",
    "Estimate your 2024 federal and state income taxes":
      "សន្និដ្ឋានពន្ធចំណូលរដ្ឋបាល និងរដ្ឋ",
    "Retirement Planner": "ផែនការសម្រាប់ការចូលនិវត្តន៍",
    "Model your path to financial independence":
      "គំរូផ្លូវទៅសេរីភាពហិរញ្ញវត្ថុ​ ក្នុងវ័យចូលនិវត្តន៍",
    "Shared finances, expense splitting and family budgeting":
      "ហិរញ្ញវត្ថុរួម, ការបែងចែកចំណាយ និងថវិកាគ្រួសារ",
    "Add Member": "បន្ថែមសមាជិក",
    "Add Family Member": "បន្ថែមសមាជិកគ្រួសារ",
    "Full Name": "ឈ្មោះពេញ",
    "Email Address": "អាសយដ្ឋានអ៊ីមែល",
    Role: "តួនាទី",
    "Financial Details": "ព័ត៌មានហិរញ្ញវត្ថុ",
    "Monthly Income ($)": "ចំណូលប្រចាំខែ ($)",
    "Budget Share ($)": "ចំណែកថវិកា ($)",
    "Add First Member": "បន្ថែមសមាជិកដំបូង",
    Overview: "ទិដ្ឋភាពទូទៅ",
    Members: "សមាជិក",
    Budgets: "ថវិកា",
    Splits: "ការបែងចែក",
    Permissions: "សិទ្ធិ",
    "Financial Dashboard": "ផ្ទាំងព័ត៌មានហិរញ្ញវត្ថុ",
    "Complete analytics overview · April 2026":
      "វិភាពត្យគ្រប់គ្រាន់ · មេសា 2026",
    Customize: "កំណត់តម្រូវ",
    "Profile Information": "ព័ត៌មានប្រវត្តិ",
    "Update your personal details and profile picture":
      "អាប់ដេតពត៌មានផ្ទាល់ខ្លួន និងរូបថតប្រវត្តិ",
    Profile: "ប្រវត្តិ",
    Notifications: "ការជូនដំណឹង",
    Security: "សុវត្ថិភាព",
    Display: "បង្ហាញ",
    Data: "ទិន្នន័យ",
    "Manage your account, preferences and security":
      "គ្រប់គ្រងគណនី, ចំណូលចិត្ត និងសុវត្ថិភាព",
    Language: "ភាសា",
    "Save Profile": "រក្សាទុកប្រវត្តិ",
    "Notification Preferences": "ចំណូលចិត្តការជូនដំណឹង",
    "Control what alerts and updates you receive":
      "គ្រប់គ្រងការជូនដំណឹងដែលអ្នកទទួល",
    "Save Preferences": "រក្សាទុកចំណូលចិត្ត",
    "Change Password": "ផ្លាស់ប្តូរពាក្យសម្ងាត់",
    "Use a strong, unique password": "ប្រើពាក្យសម្ងាត់រឹងមាំ និងមិនដូចគ្នា",
    "Security Options": "ជម្រើសសុវត្ថិភាព",
    "Save Security Settings": "រក្សាទុកការកំណត់សុវត្ថិភាព",
    "Active Sessions": "សម័យសកម្ម",
    "Display & Appearance": "ការបង្ហាញ និងទំងន់",
    "Customize how WealthPath looks and feels":
      "កំណត់របៀប WealthPath មើល និងមានអារម្មណ៍",
    "Save Display Settings": "រក្សាទុកការកំណត់បង្ហាញ",
    "Import & Export": "នាំចូល និង នាំចេញ",
    "Move your financial data in and out of WealthPath":
      "ផ្លាស់ប្តូរទិន្នន័យហិរញ្ញវត្ថុខាងក្រៅ និងចូលក្នុង WealthPath",
    "Export All Data (CSV)": "នាំចេញទិន្នន័យទាំងអស់ (CSV)",
    "Download all your data as a spreadsheet":
      "ទាញយកទិន្នន័យទាំងអស់ជាសន្លឹកគណនា",
    "Export Financial Report": "នាំចេញរបាយការណ៍ហិរញ្ញវត្ថុ",
    "Download a full PDF report of your finances":
      "ទាញយករបាយការណ៍ PDF ពេញលេញនៃហិរញ្ញវត្ថុរបស់អ្នក",
    "Export to Excel": "នាំចេញទៅ Excel",
    "Download all data in Excel format (.xlsx)":
      "ទាញយកទិន្នន័យទាំងអស់ក្នុងទ្រង់ទ្រាយ Excel (.xlsx)",
    "Export Raw Data (JSON)": "នាំចេញទិន្នន័យដើម (JSON)",
    "Machine-readable export for developers": "នាំចេញសម្រាប់អ្នកអភិវឌ្ឍន៍",
    "Connected Services": "សេវាកម្មដែលភ្ជាប់",
    "Manage external integrations": "គ្រប់គ្រងការរួមបញ្ចូលខាងក្រៅ",
    "Danger Zone": "តំបន់គ្រោះថ្នាក់",
    "Irreversible actions — proceed with caution":
      "សកម្មភាពដែលមិនអាចត្រឡប់ក្រោយបាន — ប្រយ័ត្ន",
    "Export Complete": "នាំចេញបានសម្រេច",
    "Your file has been downloaded.": "ឯកសាររបស់អ្នកត្រូវបានទាញយក។",
    Name: "ឈ្មោះ",
    "Amount ($)": "ចំនួន ($)",
    Frequency: "កាលវិភាគ",
    Category: "ប្រភេទ",
    "Due Day (1–31)": "ថ្ងៃកំណត់ (1–31)",
    "Icon Name (e.g. Home, Zap)": "ឈ្មោះរូបតំណាង (ឧ. Home, Zap)",
    "Logo URL": "អាសយដ្ឋាន រូបតំណាង",
    Add: "បន្ថែម",
  },
};

export function translateText(language, key) {
  return TRANSLATIONS[language]?.[key] ?? key;
}

export function useTranslate() {
  const { user } = useUser();
  const language = user?.language || "English";
  return (key) => translateText(language, key);
}

export const SUPPORTED_LANGUAGES = ["English", "Khmer"];
